### PR TITLE
Unit Tests for PDF lib

### PR DESCRIPTION
**Pull request by georgkrause**
This Pull Requests provides unit tests for the pdflib. Currently pdftk is used, this will be replaced. To support the implementation of the next lib, some unit tests should be in place to verify the lib does, what it is supposed to.

I am new to unit testing in Python, so these are only my first steps. Any feedback welcome.

### CODE REVIEW

**Comment by georgkrause** [comment]
I am currently verifying, the `pdftk` command is called with the correct arguments to achieve what is requested. In order to use the unit tests for the implementation it would be nice to test if the pdf files is changed as requested.

**Comment by georgkrause** [comment]
I added tests for two more functions. The commit also fixes issues I found while writing tests.

Anyway, I think the functions `split_ranges` and `cat_ranges_for_delete` are way to complicated and could be implemented with list logic way much more efficient than iteration over all items.

**Comment by ciur** [comment]
@georgkrause, so far so good!

**Comment by georgkrause** [comment]
@ciur Thanks for the feedback, I will progress in this style tomorrow. Its actually quite good to dig into a project by writing unit tests. 

I thought about the break between the current version and a version where pdftk is replaced, maybe we should allow a transition phase by implementing the new lib aside pdftk?

**Comment by ciur** [comment]
> maybe we should allow a transition phase by implementing the new lib aside pdftk?

sounds, good to me! In such case, if something goes wrong along the way, it would be easier to revert.

**Comment by georgkrause** [comment]
```
........................
----------------------------------------------------------------------
Ran 24 tests in 0.090s

OK
Name                             Stmts   Miss  Cover
----------------------------------------------------
mglib/__init__.py                    0      0   100%
mglib/conf/__init__.py               2      0   100%
mglib/conf/default_settings.py       7      0   100%
mglib/conf/settings.py              29      3    90%
mglib/exceptions.py                  2      0   100%
mglib/mime.py                       27      4    85%
mglib/path.py                       95     20    79%
mglib/pdfinfo.py                    46      9    80%
mglib/pdftk.py                     110      0   100%
mglib/runcmd.py                      8      4    50%
mglib/step.py                       28      4    86%
mglib/storage.py                   135     94    30%
mglib/test/__init__.py               0      0   100%
mglib/test/utils.py                 25      1    96%
mglib/utils.py                      55     40    27%
mglib/wrapper.py                    25      4    84%
----------------------------------------------------
TOTAL                              594    183    69%
```

`pdftk` now has a coverage of 100%, which means this can be merged from my point of view

**Comment by georgkrause** [comment]
Its rebase in order to keep a clean git log.

**Comment by ciur** [comment]
Awesome! I have seen that github actions addition, great job!

@georgkrause don't take it too far with testing. It easy to get lost in writing tests. More tests means more rigid code. There is always a golden  balance. For beginning a few tests just to prove that code works as expected - will suffice.

Please let me know when you think PR is ready to be merged.

**Comment by georgkrause** [comment]
I didn't went too far, I just tried to cover some different cases for each function. This way I can verify if my reimplementation still does what it is supposed to be.

From my point of view this can be merged. Thanks!

**Pull request merged**
