### PR TITLE
Introduce Github Actions

### PR DESCRIPTION
**Pull request by georgkrause**
This PR introduces Github Actions. Some pep8 code style linting and all unit tests are executed. Also Coverage is measured but not yet reported. It seems like https://coveralls.io/ is well integrated into Github, but I want to make sure you want to use it before implementing it.

### CODE REVIEW

**Comment by ciur** [comment]
Wow! cool!  I didn't know about this cute feat! It is a great addition to PEP8 style checks!

Danke!

**Comment by georgkrause** [comment]
@ciur You want me to bring this to papermerge, too? Are you interested in coverage reports?

**Comment by ciur** [comment]
@georgkrause, sounds like a great plan!

But there is a catch.
Papermerge is way more complex project than mglib, as result, there are modules like migrations for example which rarely are PEP8 formatted (they are auto generated). This means you will need to exclude certain modules. Another non-PEP8 compliant part are settings. Which have this ``from .base import *``.  Latter - I mean settings - has an easy fix with ``# no qa`` comment.

I would say - let's try. If it is practical we will keep it. 
Go on an create a PR, I will merge it in master branch, and let's see what happens

**Comment by georgkrause** [comment]
We are free to configure this as we like, excluding is no problem at all and makes sense for settings and migrations. Lets discuss this over there, after I filed a PR

**Pull request merged**
